### ISSUE TITLE
New website for the Example package

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/example#1]
Just to declare my further plans: use https://github.com/fingolfin/PackageMaker by @fingolfin to have a GitHub pages based Example package's website.

**Comment by alex-konovalov** [comment]
Actually, it looks to me now that at this stage, I have rather look at https://github.com/fingolfin/Demo/tree/gh-pages

**Comment by alex-konovalov** [comment]
The new website is http://gap-system.github.io/example/. I have to update meta-information in `PackageInfo.g` for the new release.

**Comment by alex-konovalov** [comment]
@gap-packages : FYI, the new website of Example package is http://gap-system.github.io/example/ and it's now switched to https://github.com/fingolfin/ReleaseTools.

(adding the comment to check if `@gap-packages` will cause a notification sent to all members of the gap-packages organisation)

**Comment by james-d-mitchell** [comment]
Hi Alex

I get a 404 when I click the link.


Best

Jamea

**Comment by alex-konovalov** [comment]
Oops, sorry - it's http://gap-packages.github.io/example/
